<?php
$arr = [
    "Home",
    "About Us",
    "Services",
    "Blog",
    "FAQ",
    "Contact",
    "Plan",
    "Login",
    "Logout",
    "Sign up",
    "Copyright",
    "All Rights Reserved",
    "Username",
    "Email Or Username",
    "Password",
    "Phone",
    "Send Reset Passsword Link",
    "Create New Account",
    "Read More",
    "Login here",
    "Our Office",
    "Follow us on",
    "Remember Me",
    "Forgot password?",
    "Don't have any account? Sign Up",
    "SIGN UP FORM",
    "Sponsor By",
    "First Name",
    "Last Name",
    "Email Address",
    "Your Phone Number",
    "Confirm Password",
    "Already have an account? Login",
    "Please confirm your password before continuing.",
    "Forgot Your Password?",
    "Already have an account?",
    "Reset Password",
    "Enter your Email Address",
    "Don't have an account?",
    "Send Password Reset Link",
    "New Password",
    "Register Here",
    "Recover Password",
    "Create account",
    "403 Forbidden",
    "Learn More",
    "You don’t have permission to access ‘/’ on this server.",
    "Back To Home",
    "Sorry page was not found!",
    "We're sorry, the page you requested could not be found. Please go back to the homepage or contact us at",
    "Method not allowed",
    "opps!",
    "Join Now",
    "Know More",
    "Session has expired",
    "Dashboard",
    "Feel Free To Conatct Us",
    "Bonus",
    "The affiliate program is working up to 3 refaral levels. To join to the affiliate program, you should have ac active deposit in the project.",
    "CryptoVest provide an adaptive and profitable affiliate program for long-term pertnership. You will receive referal commisiona from your pertner's deposit and also from his daily income.",
    "Affiliate program",
    "Refer us to your friends!",
    "How it works",
    "Invest History",
    "Add Fund",
    "Yes",
    "login your account",
    "Get On First Level Refferal Commission",
    "Referral Bonus Level",
    "Fund History",
    "Transaction",
    "Payout",
    "Payout History",
    "My Referral",
    "Referral Bonus",
    "Profile Settings",
    "Support Ticket",
    "Main Balance",
    "Interest Balance",
    "Total Deposit",
    "Total Earn",
    "Account Statistics",
    "Total Invest",
    "Total Payout",
    "Total Ticket",
    "Total Referral Bonus",
    "Latest Registered Partner",
    "The last Referral Bonus",
    "Email",
    "Phone Number",
    "Joined At",
    "Code",
    "Pay Now",
    "Payment By",
    "Two Factor Authenticator",
    "Enable Two Factor Authenticator",
    "Disable Two Factor Authenticator",
    "Google Authenticator",
    "DOWNLOAD APP",
    "Verify Your OTP",
    "Close",
    "Verify",
    "Verify Your OTP to Disable",
    "Transactions",
    "Search for Transaction ID",
    "Remark",
    "Search",
    "SL No.",
    "Transaction ID",
    "Amount",
    "Remarks",
    "Time",
    "Type Here",
    "All Payment",
    "Complete Payment",
    "Pending Payment",
    "Cancel Payment",
    "Gateway",
    "Charge",
    "Search Service",
    "Subject",
    "Image Upload",
    "Upload",
    "Last Reply",
    "Reply",
    "Open",
    "Answered",
    "Customer Reply",
    "Closed",
    "Upload File",
    "Confirm",
    "Are you want to close ticket?",
    "My Profile",
    "Open Ticket",
    "Show Ticket",
    "No Data found",
    "Email Verification",
    "Update User",
    "Update Password",
    "Admin Feedback",
    "PAYOUT NOW",
    "Transaction Limit:",
    "Payout By",
    "Remove",
    "Last Deposit",
    "Admin",
    "Last Withdrawal",
    "Confirm Now",
    "Return Interest",
    "Received Amount",
    "Upcoming Payment",
    "Search User",
    "Bonus From",
    "Current Password",
    "Address",
    "Submit",
    "Useful Links",
    "Deposit Balance",
    "2FA Security",
    "Referral Link",
    "Level",
    "level",
];
return $arr;
